# i changed somthing in the code and it works now
version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3000:80"
  frontend:
    build:
      context: ./frontend
  backend:
    build:
      context: ./backend
  
