# version: "3"
# services:
#   nginx:
#     restart: always
#     build:
#       context: ./nginx
#     ports:
#       - "3000:80"
#       - "8000:90"
#   frontend:
#     build:
#       context: ./frontend
#   backend:
#     build:
#       context: ./backend
version: '3'
services:
  backend:
    build: .
    ports:
      - 8000:8000
  frontend:
    build: .
    ports:
      - 3000:3000


  
