name: Droplet Pipeline
on:
  push:
    branches: [depl]
jobs:
  push_to_droplet:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: depl
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
      - name: Run Docker Compose
        run: docker-compose up --build -d